In [16]:
#data handling/modeling
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import scipy.stats as stats

# visualization
%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
data = pd.read_csv("Motor_Vehicle_Crashes.csv")
print(data.dtypes)
print(data.shape)

C:\Users\jeffr\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

CRASH DATE                        object
CRASH TIME                        object
BOROUGH                           object
ZIP CODE                          object
LATITUDE                         float64
LONGITUDE                        float64
LOCATION                          object
ON STREET NAME                    object
CROSS STREET NAME                 object
OFF STREET NAME                   object
NUMBER OF PERSONS INJURED        float64
NUMBER OF PERSONS KILLED         float64
NUMBER OF PEDESTRIANS INJURED      int64
NUMBER OF PEDESTRIANS KILLED       int64
NUMBER OF CYCLIST INJURED          int64
NUMBER OF CYCLIST KILLED           int64
NUMBER OF MOTORIST INJURED         int64
NUMBER OF MOTORIST KILLED          int64
CONTRIBUTING FACTOR VEHICLE 1     object
CONTRIBUTING FACTOR VEHICLE 2     object
CONTRIBUTING FACTOR VEHICLE 3     object
CONTRIBUTING FACTOR VEHICLE 4     object
CONTRIBUTING FACTOR VEHICLE 5     object
COLLISION_ID                       int64
VEHICLE TYPE CODE 1               object
VEHICLE TYPE CODE 2               object
VEHICLE TYPE CODE 3               object
VEHICLE TYPE CODE 4               object
VEHICLE TYPE CODE 5               object
dtype: object
(1665588, 29)

In [18]:
#import geopandas as gpd

In [21]:
data.head()

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,11/07/2019,8:10,NaN,NaN,40.887352,-73.905340,POINT (-73.90534 40.887352),WEST 238 STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4237328,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1,11/27/2019,13:31,NaN,NaN,40.664948,-73.942620,POINT (-73.94262 40.664948),KINGSTON AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4251305,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,11/17/2019,9:15,QUEENS,11374,40.726185,-73.870220,POINT (-73.87022 40.726185),WOODHAVEN BOULEVARD,62 ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4242260,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
3,12/01/2019,1:09,BRONX,10459,40.820984,-73.891624,POINT (-73.891624 40.820984),EAST 163 STREET,SOUTHERN BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,4250971,Sedan,Sedan,NaN,NaN,NaN
4,11/07/2019,18:00,NaN,NaN,NaN,NaN,NaN,FLATBUSH AVENUE,EASTERN PARKWAY,NaN,...,Unspecified,NaN,NaN,NaN,4237356,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN

In [22]:
feature_cols = data.columns[10:18]

In [23]:
x = data[feature_cols].copy()
x

,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED
0,0.0,0.0,0,0,0,0,0,0
1,0.0,0.0,0,0,0,0,0,0
2,0.0,0.0,0,0,0,0,0,0
3,0.0,0.0,0,0,0,0,0,0
4,0.0,0.0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
1665583,0.0,0.0,0,0,0,0,0,0
1665584,1.0,0.0,1,0,0,0,0,0
1665585,0.0,0.0,0,0,0,0,0,0
1665586,1.0,0.0,0,0,1,0,0,0
1665587,0.0,0.0,0,0,0,0,0,0

In [24]:
x = x[x['NUMBER OF PERSONS INJURED']>0]
x = x.dropna()
pred = x['NUMBER OF PERSONS INJURED']
resp = x['NUMBER OF PERSONS KILLED']
pred.dropna()
resp.dropna()
pred = np.array(x['NUMBER OF PERSONS INJURED'])
resp = np.array(x['NUMBER OF PERSONS KILLED'])
pred = pred.reshape(-1,1)
resp = resp.reshape(-1,1)
#print(x['NUMBER OF PERSONS INJURED'].isnull() = True)

In [25]:
linreg = LinearRegression()
linreg.fit(pred,resp)
resp_pred = linreg.predict(pred)
print("The slope is:",linreg.coef_,"The y-intercept is",linreg.intercept_)
print("The R^2 is:",metrics.r2_score(resp,resp_pred))
print("The MSE is:",metrics.mean_squared_error(resp,resp_pred))

The slope is: [[0.00211087]] The y-intercept is [-0.00129838]
The R^2 is: 0.001578449580979191
The MSE is: 0.0021256075081635905

In [26]:
data.head()

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,11/07/2019,8:10,NaN,NaN,40.887352,-73.905340,POINT (-73.90534 40.887352),WEST 238 STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4237328,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1,11/27/2019,13:31,NaN,NaN,40.664948,-73.942620,POINT (-73.94262 40.664948),KINGSTON AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4251305,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,11/17/2019,9:15,QUEENS,11374,40.726185,-73.870220,POINT (-73.87022 40.726185),WOODHAVEN BOULEVARD,62 ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4242260,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
3,12/01/2019,1:09,BRONX,10459,40.820984,-73.891624,POINT (-73.891624 40.820984),EAST 163 STREET,SOUTHERN BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,4250971,Sedan,Sedan,NaN,NaN,NaN
4,11/07/2019,18:00,NaN,NaN,NaN,NaN,NaN,FLATBUSH AVENUE,EASTERN PARKWAY,NaN,...,Unspecified,NaN,NaN,NaN,4237356,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN

In [27]:
new_data = pd.DataFrame()
cols_of_interest = data[['CRASH TIME','BOROUGH','NUMBER OF PERSONS INJURED','NUMBER OF PERSONS KILLED','CONTRIBUTING FACTOR VEHICLE 1','CONTRIBUTING FACTOR VEHICLE 2']]
new_data = cols_of_interest
#is it right to drop NA values this early? What is being dropped
new_data.dropna()

,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2
2,9:15,QUEENS,0.0,0.0,Driver Inattention/Distraction,Unspecified
3,1:09,BRONX,0.0,0.0,Unspecified,Unspecified
6,17:30,BROOKLYN,0.0,0.0,Unspecified,Unspecified
7,8:00,QUEENS,0.0,0.0,Driver Inexperience,Unspecified
8,8:09,BROOKLYN,0.0,0.0,Backing Unsafely,Driver Inattention/Distraction
...,...,...,...,...,...,...
1665582,20:14,BRONX,0.0,0.0,Unspecified,Unspecified
1665583,10:45,MANHATTAN,0.0,0.0,Lost Consciousness,Unspecified
1665585,14:30,STATEN ISLAND,0.0,0.0,Unspecified,Unspecified
1665586,12:27,BROOKLYN,1.0,0.0,Unspecified,Unspecified
1665587,17:37,QUEENS,0.0,0.0,Unspecified,Unspecified

In [28]:
def borough_to_numeric(x):
    if x=='MANHATTAN':
        return 1
    if x=='BROOKLYN':
        return 2
    if x=='QUEENS':
        return 3
    if x=='BRONX':
        return 4
    if x=='STATEN ISLAND':
        return 5
    else:
        return 0
#creates dummy variable 1 for day and 0 for night  
def time_to_day_night(x):
    h,m = x.split(':')
    h = int(h)
    m = int(m)
    if h >= 12:
        return 1
    else:
        return 0

In [29]:
new_data['CRASH TIME'] = new_data['CRASH TIME'].apply(time_to_day_night)
new_data['BOROUGH'] = new_data['BOROUGH'].apply(borough_to_numeric)
new_data

C:\Users\jeffr\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\jeffr\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2
0,0,0,0.0,0.0,Unspecified,Unspecified
1,1,0,0.0,0.0,Driver Inattention/Distraction,Unspecified
2,0,3,0.0,0.0,Driver Inattention/Distraction,Unspecified
3,0,4,0.0,0.0,Unspecified,Unspecified
4,1,0,0.0,0.0,Driver Inattention/Distraction,Unspecified
...,...,...,...,...,...,...
1665583,0,1,0.0,0.0,Lost Consciousness,Unspecified
1665584,1,0,1.0,0.0,Unspecified,NaN
1665585,1,5,0.0,0.0,Unspecified,Unspecified
1665586,1,2,1.0,0.0,Unspecified,Unspecified
1665587,1,3,0.0,0.0,Unspecified,Unspecified

In [56]:
new_data['NUMBER OF PERSONS AFFECTED'] = new_data['NUMBER OF PERSONS KILLED'] + new_data['NUMBER OF PERSONS INJURED']
new_data.tail(50)

C:\Users\jeffr\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,NUMBER OF PERSONS AFFECTED
1665538,1,0,3.0,0.0,Fatigued/Drowsy,Outside Car Distraction,3.0
1665539,0,4,1.0,0.0,Driver Inattention/Distraction,Unspecified,1.0
1665540,1,0,0.0,0.0,Unspecified,Unspecified,0.0
1665541,1,2,0.0,0.0,Unspecified,Unspecified,0.0
1665542,0,2,0.0,0.0,Unspecified,Unspecified,0.0
1665543,1,2,0.0,0.0,Unspecified,Unspecified,0.0
1665544,1,1,0.0,0.0,Unspecified,Unspecified,0.0
1665545,1,2,0.0,0.0,Unspecified,Unspecified,0.0
1665546,0,0,1.0,0.0,Unspecified,Unspecified,1.0
1665547,1,0,0.0,0.0,Outside Car Distraction,Unspecified,0.0
1665548,1,1,0.0,0.0,Unspecified,Unspecified,0.0
1665549,0,1,0.0,0.0,Other Vehicular,Other Vehicular,0.0
1665550,1,1,0.0,0.0,Driver Inattention/Distraction,Unspecified,0.0
1665551,0,2,0.0,0.0,Turning Improperly,Unspecified,0.0
1665552,1,2,0.0,0.0,Unspecified,Unspecified,0.0
1665553,0,0,0.0,0.0,Failure to Yield Right-of-Way,Unspecified,0.0
1665554,1,4,0.0,0.0,Unspecified,NaN,0.0
1665555,0,2,0.0,0.0,Unspecified,Unspecified,0.0
1665556,1,2,0.0,0.0,Failure to Yield Right-of-Way,Unspecified,0.0
1665557,1,1,0.0,0.0,Lost Consciousness,Unspecified,0.0
1665558,0,0,0.0,0.0,Unspecified,NaN,0.0
1665559,1,0,1.0,0.0,Unspecified,Unspecified,1.0
1665560,1,3,0.0,0.0,Unspecified,Unspecified,0.0
1665561,0,1,0.0,0.0,Other Vehicular,Driver Inattention/Distraction,0.0
1665562,1,2,0.0,0.0,Unspecified,Unspecified,0.0
1665563,1,0,0.0,0.0,Fatigued/Drowsy,Fatigued/Drowsy,0.0
1665564,1,1,0.0,0.0,Unspecified,Unspecified,0.0
1665565,0,0,0.0,0.0,Unspecified,Unspecified,0.0
1665566,1,1,0.0,0.0,Driver Inattention/Distraction,Unspecified,0.0
1665567,0,0,0.0,0.0,Unspecified,Unspecified,0.0
1665568,1,3,1.0,0.0,Unspecified,NaN,1.0
1665569,1,0,0.0,0.0,Unspecified,Unspecified,0.0
1665570,1,5,0.0,0.0,Unspecified,Unspecified,0.0
1665571,0,0,0.0,0.0,Unspecified,Unspecified,0.0
1665572,1,2,0.0,0.0,Unspecified,Unspecified,0.0
1665573,1,3,0.0,0.0,Unspecified,Unspecified,0.0
1665574,1,2,1.0,0.0,Unspecified,Unspecified,1.0
1665575,1,1,0.0,0.0,Unspecified,Unspecified,0.0
1665576,0,3,0.0,0.0,Unspecified,NaN,0.0
1665577,1,1,0.0,0.0,Unspecified,Unspecified,0.0
1665578,1,1,0.0,0.0,Unspecified,Unspecified,0.0
1665579,1,2,1.0,0.0,Unspecified,NaN,1.0
1665580,1,1,0.0,0.0,Unspecified,Unspecified,0.0
1665581,1,3,0.0,0.0,Fatigued/Drowsy,Unspecified,0.0
1665582,1,4,0.0,0.0,Unspecified,Unspecified,0.0
1665583,0,1,0.0,0.0,Lost Consciousness,Unspecified,0.0
1665584,1,0,1.0,0.0,Unspecified,NaN,1.0
1665585,1,5,0.0,0.0,Unspecified,Unspecified,0.0
1665586,1,2,1.0,0.0,Unspecified,Unspecified,1.0
1665587,1,3,0.0,0.0,Unspecified,Unspecified,0.0

In [55]:
feature_list = ['CRASH TIME','BOROUGH']
x_mult = new_data[feature_list]
y_mult = new_data['NUMBER OF PERSONS AFFECTED']

mult_linreg = LinearRegression()
mult_linreg.fit(x_mult,y_mult)

print('The y-intercept is:', mult_linreg.intercept_)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
}