In [4]:
#data handling/modeling
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import scipy.stats as stats
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib
from sklearn.cluster import KMeans
import seaborn as sns; sns.set()
import csv
from random import seed
from random import randrange
from csv import reader
from math import sqrt
from sklearn.neighbors import KNeighborsClassifier

#svm
from sklearn import datasets
from sklearn import svm 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

#geotools
import geopy
import geocoder
import geopandas as gpd
from geopandas.tools import geocode
from geopy.geocoders import Nominatim

In [2]:
data = pd.read_csv("Motor_Vehicle_Crashes.csv")
print(data.dtypes)
print(data.shape)

C:\Users\jeffr\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

CRASH DATE                        object
CRASH TIME                        object
BOROUGH                           object
ZIP CODE                          object
LATITUDE                         float64
LONGITUDE                        float64
LOCATION                          object
ON STREET NAME                    object
CROSS STREET NAME                 object
OFF STREET NAME                   object
NUMBER OF PERSONS INJURED        float64
NUMBER OF PERSONS KILLED         float64
NUMBER OF PEDESTRIANS INJURED      int64
NUMBER OF PEDESTRIANS KILLED       int64
NUMBER OF CYCLIST INJURED          int64
NUMBER OF CYCLIST KILLED           int64
NUMBER OF MOTORIST INJURED         int64
NUMBER OF MOTORIST KILLED          int64
CONTRIBUTING FACTOR VEHICLE 1     object
CONTRIBUTING FACTOR VEHICLE 2     object
CONTRIBUTING FACTOR VEHICLE 3     object
CONTRIBUTING FACTOR VEHICLE 4     object
CONTRIBUTING FACTOR VEHICLE 5     object
COLLISION_ID                       int64
VEHICLE TYPE CODE 1               object
VEHICLE TYPE CODE 2               object
VEHICLE TYPE CODE 3               object
VEHICLE TYPE CODE 4               object
VEHICLE TYPE CODE 5               object
NUMTIME                          float64
dtype: object
(1048575, 30)

In [3]:
data = data[['BOROUGH','NUMTIME','LONGITUDE','LATITUDE','NUMBER OF PERSONS KILLED','NUMBER OF PERSONS INJURED','NUMBER OF PEDESTRIANS KILLED','NUMBER OF PEDESTRIANS INJURED']]
data['PERSONS_AFFECTED'] = data['NUMBER OF PERSONS KILLED'] + data['NUMBER OF PERSONS INJURED']
data['PEDESTRIANS_AFFECTED'] = data['NUMBER OF PEDESTRIANS KILLED'] + data['NUMBER OF PEDESTRIANS INJURED']
data = data.drop(['NUMBER OF PERSONS KILLED','NUMBER OF PERSONS INJURED','NUMBER OF PEDESTRIANS INJURED','NUMBER OF PEDESTRIANS KILLED'],axis=1)
def borough(x):
    if x=="QUEENS":
        return 1
    if x=='BROOKLYN':
        return 2
    if x=='MANHATTAN':
        return 3
    if x=='BRONX':
        return 4
    if x=='STATEN ISLAND':
        return 5
data['BOROUGH'] = data['BOROUGH'].apply(borough)
data = data.dropna()
data = data[data.LONGITUDE !=0]
data['PERSONS_TF']=0
data.loc[data['PERSONS_AFFECTED'] > 0, 'PERSONS_TF']= 1
data.loc[data['PERSONS_AFFECTED'] == 0, 'PERSONS_TF']= 0
data.head(20)

,BOROUGH,NUMTIME,LONGITUDE,LATITUDE,PERSONS_AFFECTED,PEDESTRIANS_AFFECTED,PERSONS_TF
2,1.0,9.25,-73.870220,40.726185,0.0,0,0
3,4.0,1.15,-73.891624,40.820984,0.0,0,0
6,2.0,17.50,-73.946430,40.624382,0.0,0,0
7,1.0,8.00,-73.791720,40.679310,0.0,0,0
8,2.0,8.15,-73.899796,40.644226,0.0,0,0
13,1.0,12.42,-73.740820,40.718754,1.0,0,1
14,4.0,14.50,-73.868164,40.847130,0.0,0,0
16,1.0,9.15,-73.740800,40.660965,0.0,0,0
17,2.0,14.58,-73.975700,40.678800,0.0,0,0
18,3.0,7.70,-73.957710,40.779495,0.0,0,0
21,3.0,2.25,-73.992150,40.759100,0.0,0,0
22,2.0,21.25,-73.939780,40.694960,0.0,0,0
23,2.0,12.00,-73.959984,40.683918,0.0,0,0
25,1.0,22.12,-73.907570,40.768303,0.0,0,0
27,3.0,4.08,-73.973050,40.752693,0.0,0,0
28,2.0,10.67,-73.941170,40.653150,0.0,0,0
31,4.0,14.37,-73.885956,40.858850,2.0,0,1
32,2.0,6.92,-73.970330,40.588380,1.0,0,1
33,1.0,8.62,-73.879074,40.711160,3.0,1,1
35,4.0,9.50,-73.898026,40.895985,0.0,0,0

In [20]:
#Gridsearch will provide 
model = KNeighborsClassifier(n_neighbors=5)
pred = list(zip(data['NUMTIME'],data['LONGITUDE'],data['LATITUDE'],data['PERSONS_TF']))
resp = data['BOROUGH']
model.fit(pred,resp)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [23]:
X_train,X_test,y_train,y_test = train_test_split(pred,resp,test_size = .3)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy is:",metrics.accuracy_score(y_test,y_pred))

Accuracy is: 0.9881719176797904

In [24]:
pred = list(zip(data['NUMTIME'],data['BOROUGH']))
resp = data['PERSONS_TF']
X_train,X_test,y_train,y_test = train_test_split(pred,resp,test_size = .3)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy is:",metrics.accuracy_score(y_test,y_pred))

Accuracy is: 0.7682222909181207

In [ ]:
#do gridsearch and add features
#confusion matrix
#contributing factor and cyclist 
#svm?